## 01 SVM
scikit-learn 와인 데이터셋을 각기 다른 hyperparameter (kernel, C, gamma) 조합의 SVM으로 분류해보고, 가장 성능이 좋았던 hyperparameter 조합을 알려주세요.

https://noanomal.tistory.com/81?
- 위 링크는 와인 데이터셋을 사용하는 방법을 간단하게 정리한 블로그입니다.

In [28]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
import pandas as pd
from sklearn.datasets import load_wine
wine = load_wine()
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df['class'] = wine.target

df.tail()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
173        0.61                  0.52             1.06              7.7  0.64   
174        0.75                  0.43             1.41              7.3  0.70   
175        0.69                  0.43             1.35             10.2  0.59   
176        0.68                  0.53             1.46              9.3  0.60   
177        0.76                  0.56             1.35              9.2  0.61   

     od280/od315_of_diluted_wines  proline  class  
173                          1.74    740.0      2  
174                          1.56    750.0      2  
175                          1.56    835.0      2  
176                          1.62    840.0      2  
177                          1.60    560.0      2

In [30]:
df.iloc[:,:13]

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [31]:
df.iloc[:, -1]

0      0
1      0
2      0
3      0
4      0
      ..
173    2
174    2
175    2
176    2
177    2
Name: class, Length: 178, dtype: int32

In [32]:
X = df.iloc[:,:13].values

In [33]:
y = df.iloc[:,-1].values

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [36]:
X_train.shape

(142, 13)

In [37]:
X_test.shape

(36, 13)

In [38]:
y_train.shape

(142,)

In [39]:
y_test.shape

(36,)

In [40]:
from sklearn.preprocessing import StandardScaler

In [41]:
scaler = StandardScaler()

In [42]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

# (1) 기본값 SVM

In [43]:
from sklearn.svm import SVC

In [44]:
svm = SVC()

In [45]:
svm.fit(X_train, y_train)

SVC()

In [46]:
svm.predict(X_test)

array([1, 0, 2, 1, 1, 1, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2, 2, 2, 0,
       1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 0, 1, 2, 1])

In [47]:
y_test

array([1, 0, 2, 1, 1, 1, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2, 2, 1, 0,
       1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 0, 1, 2, 1])

In [48]:
svm.predict(X_test) == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [49]:
np.mean(svm.predict(X_test) == y_test)

0.9722222222222222

### (2) hyperparameter 1: kernel의 차이에 따른 분류 성능

In [53]:
svm_linear = SVC(kernel='linear')
svm_poly = SVC(kernel='poly')
svm_rbf = SVC(kernel='rbf')

In [54]:
svm_linear.fit(X_train, y_train)
svm_poly.fit(X_train, y_train)
svm_rbf.fit(X_train, y_train)

SVC()

In [55]:
print(f'prediction accuracy of linear kernel is {np.mean(svm_linear.predict(X_test) == y_test)}')
print(f'prediction accuracy of poly kernel is {np.mean(svm_poly.predict(X_test) == y_test)}')
print(f'prediction accuracy of rbf kernel is {np.mean(svm_rbf.predict(X_test) == y_test)}')

prediction accuracy of linear kernel is 0.9722222222222222
prediction accuracy of poly kernel is 0.9444444444444444
prediction accuracy of rbf kernel is 0.9722222222222222


### (3) hyperparameter 2: C의 차이에 따른 분류 성능

In [56]:
svm_C1 = SVC(C=1)
svm_C8 = SVC(C=8)
svm_C10 = SVC(C=10)

In [57]:
svm_C1.fit(X_train, y_train)
svm_C8.fit(X_train, y_train)
svm_C10.fit(X_train, y_train)

SVC(C=10)

In [58]:
print(f'prediction accuracy of C=1 is {np.mean(svm_C1.predict(X_test) == y_test)}')
print(f'prediction accuracy of C=8 is {np.mean(svm_C8.predict(X_test) == y_test)}')
print(f'prediction accuracy of C=10 is {np.mean(svm_C10.predict(X_test) == y_test)}')

prediction accuracy of C=1 is 0.9722222222222222
prediction accuracy of C=8 is 0.9444444444444444
prediction accuracy of C=10 is 0.9444444444444444


### (4) hyperparamete 3: gamma의 차이에 따른 분류 성능

In [59]:
svm_gamma01 = SVC(gamma=0.1)
svm_gamma1 = SVC(gamma=1)
svm_gamma10 = SVC(gamma=10)

In [60]:
svm_gamma01.fit(X_train, y_train)
svm_gamma1.fit(X_train, y_train)
svm_gamma10.fit(X_train, y_train)

SVC(gamma=10)

In [61]:
print(f'prediction accuracy of gamma=0.1 is {np.mean(svm_gamma01.predict(X_test) == y_test)}')
print(f'prediction accuracy of gamma=1 is {np.mean(svm_gamma1.predict(X_test) == y_test)}')
print(f'prediction accuracy of gamma=10 is {np.mean(svm_gamma10.predict(X_test) == y_test)}')

prediction accuracy of gamma=0.1 is 0.9722222222222222
prediction accuracy of gamma=1 is 0.7222222222222222
prediction accuracy of gamma=10 is 0.4444444444444444
