In [1]:
!pip install numpy

   ---------------------------------------- 14.0/14.0 MB 23.4 MB/s eta 0:00:00


In [2]:
import numpy as np

In [6]:
x = np.array([3,1,2])

In [7]:
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [12]:
x = np.array([[0,3], [2,2]])

In [13]:
x

array([[0, 3],
       [2, 2]])

In [14]:
ind = np.argsort(x, axis=0) # sorts along first axis (down)

In [15]:
ind

array([[0, 1],
       [1, 0]], dtype=int64)

In [16]:
np.take_along_axis(x, ind, axis=0) #same

array([[0, 2],
       [2, 3]])

In [17]:
ind = np.argsort(x, axis=1) # sorts along last axis (across)

In [18]:
ind

array([[0, 1],
       [0, 1]], dtype=int64)

In [19]:
np.take_along_axis(x,ind,axis=1) #same

array([[0, 3],
       [2, 2]])

In [20]:
ind = np.unravel_index(np.argsort(x, axis=None), x.shape)

In [21]:
ind

(array([0, 1, 1, 0], dtype=int64), array([0, 0, 1, 1], dtype=int64))

In [23]:
x[ind] #same as np.sort(x, axis = None)

array([0, 2, 2, 3])

In [25]:
x = np.array([(1,0), (0,1)], dtype = [('x', '<i4'), ('y', '<i4')])

In [26]:
x

array([(1, 0), (0, 1)], dtype=[('x', '<i4'), ('y', '<i4')])

In [27]:
np.argsort(x, order = ('x', 'y'))

array([1, 0], dtype=int64)

In [28]:
np.argsort(x, order = ('y', 'x'))

array([0, 1], dtype=int64)

# 2번

In [29]:
import numpy as np

In [30]:
x = np.array([3,1,2])

In [31]:
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [32]:
x = np.array([[0,3], [2,2]])

In [33]:
x

array([[0, 3],
       [2, 2]])

In [34]:
ind = np.argsort(x, axis=0) #sorts along first axis(down)

In [35]:
ind

array([[0, 1],
       [1, 0]], dtype=int64)

In [36]:
np.take_along_axis(x, ind, axis = 0) #same as np.sort(x, axis=0)

array([[0, 2],
       [2, 3]])

In [37]:
ind = np.argsort(x, axis=1)

In [38]:
ind

array([[0, 1],
       [0, 1]], dtype=int64)

In [41]:
np.take_along_axis(x, ind, axis=1)

array([[0, 3],
       [2, 2]])

In [42]:
ind = np.unravel_index(np.argsort(x,axis=None), x.shape)

In [43]:
ind

(array([0, 1, 1, 0], dtype=int64), array([0, 0, 1, 1], dtype=int64))

In [44]:
import numpy as np

In [45]:
# create NumPy array

In [46]:
my_array = np.array([1,2,2,3,5,6,7,10,12,14])

In [47]:
#view NumPy array

In [48]:
my_array

array([ 1,  2,  2,  3,  5,  6,  7, 10, 12, 14])

In [49]:
#filter for values less than 5

In [50]:
my_array[(my_array < 5)]

array([1, 2, 2, 3])

In [51]:
# filter for values greater than 5

In [52]:
my_array[(my_array > 5)]

array([ 6,  7, 10, 12, 14])

In [53]:
#filter for values equal to 5

In [54]:
my_array[(my_array == 5)]

array([5])

In [55]:
# filter for values less than 5 or greater than 9

In [56]:
my_array[(my_array < 5) | (my_array > 9)]

array([ 1,  2,  2,  3, 10, 12, 14])

In [57]:
#filter for values greater than 5 and less than 9

In [58]:
my_array[(my_array > 5) & (my_array < 9)]

array([6, 7])

In [59]:
my_array[np.in1d(my_array, [2,3,5,12])]

array([ 2,  2,  3,  5, 12])